### PR TITLE
chore: Codeclimate deployment action

### PR DESCRIPTION
**Pull request by Ahmed-CIO**
Adding an action `on successful deployment` to relay that to our CodeClimate setup

### CODE REVIEW

**Review by stephen-pope-customer-io — APPROVED** [review]
Looks good

**Review by Shahroz16 — APPROVED** [review]

**Review by levibostian — APPROVED** [review]
Changed the base branch to this repo's default branch: `beta`. 

After that change, I approve.

**Comment by levibostian** [comment]
Oh, sorry Ahmed. I see in the timeline that you changed the branch to `master`. I undid your change without seeing that you did that.

**Comment by Ahmed-CIO** [comment]
no worries. I will sync with you before merging to make sure things are setup right

**Pull request merged**
